### ISSUE TITLE
cookiecutter.exceptions.ContextDecodingException when generating template on windows

### ISSUE THREAD

**Issue by dadyarri** [cookiecutter/cookiecutter#1533] opened 2021-04-25 11:34 UTC
* Cookiecutter version: 1.7.2
* Template project url: https://github.com/dadyarri/lab-work-template/
* Python version: 3.9.1
* Operating System: Windows 10

### Description:

Building template and getting `UnicodeDecodeError` and `cookiecutter.exceptions.ContextDecodingException`. On linux all works correctly

```python
C:\Users\nibezo\Desktop\Python\lab-work-template>cookiecutter gh:dadyarri/lab-work-template
Traceback (most recent call last):
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\site-packages\cookiecutter\generate.py", line 91, in generate_context
    obj = json.load(file_handle, object_pairs_hook=OrderedDict)
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 548: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\nibezo\AppData\Local\Programs\Python\Python39\Scripts\cookiecutter.exe\__main__.py", line 7, in <module>
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\site-packages\cookiecutter\cli.py", line 140, in main
    cookiecutter(
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\site-packages\cookiecutter\main.py", line 85, in cookiecutter
    context = generate_context(
  File "c:\users\nibezo\appdata\local\programs\python\python39\lib\site-packages\cookiecutter\generate.py", line 101, in generate_context
    raise ContextDecodingException(our_exc_message)
cookiecutter.exceptions.ContextDecodingException: JSON decoding error while loading "C:\Users\nibezo\.cookiecutters\lab-work-template\cookiecutter.json".  Decoding error details: "'charmap' codec can't decode byte 0x98 in position 548:
 character maps to <undefined>"
```

### What I've run:

```
cookiecutter gh:dadyarri/lab-work-template
```

**Comment by simobasso** [comment] 2021-04-26 20:54
@dadyarri, thanks for reporting.

I suppose we are trying to load the `cookiecutter.json` with the wrong encoding.

I've just checked the files in your examples, and can I ask you to remove all non-ASCII character to ensure that is an encoding problem, please?

Thanks

**Comment by dadyarri** [comment] 2021-04-26 20:56
@simobasso, thanks for answer, i tried without non-ascii characters, same situation.
But if i manually change json file's encoding to ansi, it will work

**Comment by dadyarri** [comment] 2021-05-09 09:57
Any updates?

**Comment by simobasso** [comment] 2021-05-12 21:44
Hey @dadyarri 👋 ,

It seems a bug, a duplicate of https://github.com/cookiecutter/cookiecutter/issues/943.

Maybe you can get more info there, especially on the linked issues from external repositories.

Please let me know

**Comment by dadyarri** [comment] 2021-05-13 14:11
As far as i understand, the problem in the old issue was in pipe symbol in filename (jinja filters). Well, i tried to remove them in file content. Nothing changed.

Have no idea why template isn't working

**Comment by simobasso** [comment] 2021-05-15 08:10
@dadyarri I think the problem is that the `0x98` char doesn't exist on CP1252 charset.

I suppose that the problem is already fixed in https://github.com/cookiecutter/cookiecutter/pull/1414 but is not released yet.

Could you please install the latest version of cookiecutter with `pip install git+https://github.com/cookiecutter/cookiecutter.git` and check if fix the bug?

Thanks 🙏

**Comment by dadyarri** [comment] 2021-05-17 02:10
@simobasso, hello. installed git version, and yes it is worked.

but now i'm getting error with custom extension (`Unable to load extension: No module named 'extensions'`). Can you help with it?

**Closed** 2021-05-17 13:17 UTC
Labels: bug, duplicate, windows

**Comment by simobasso** [comment] 2021-05-21 14:58
@dadyarri, thanks for the update! We hope to release the 2.0.0 soon!

**Comment by dadyarri** [comment] 2021-05-27 07:37
@simobasso, hi. Could you check the discussions? I've got a problem with custom extensions
