### ISSUE TITLE
A hook or configuration to check the version of cookiecutter library

### ISSUE THREAD

**Issue by wenjuno** [cookiecutter/cookiecutter#1921] opened 2023-08-15 02:54 UTC
It is great there are new features added to each release of cookiecutter library. But as I publish cookiecutter templates as plain files (via git repositories), I struggle to limit the version of the cookiecutter library users use to generate from the templates. Sometimes users can use an older version of cookiecutter and run into weird behavior. For instance, the human readable prompts is implemented in 2.2.0 and when used with older cookiecutter it will print bizarre prompts and stall the selection phase. Currently, the pre-generate hook runs after the selection phase so it doesn't help in such case. I would love to have either a pre-run hook to check or a configuration in cookiecutter.json to specify the version spec of cookiecutter (I'm thinking not just a minimum supported version but also the maximum to guard against breaking changes in newer major release of cookiecutter that don't work with older templates). Thanks.

**Comment by ericof** [comment] 2023-09-22 12:51
Duplicate of #1855

**Closed by ericof** 2023-09-22 12:51 UTC
Labels: duplicate
