### ISSUE TITLE
Controlling the permission of templated files or directories (Linux).

### ISSUE THREAD

**Issue by grabear** [cookiecutter/cookiecutter#1163] opened 2019-04-11 06:36 UTC
I'm using the cookiecutter function to dynamically create directories:

```python
   def setup_templates(self):
        self.logger.debug("Setting up templated files...")
        activator_cookie = self.cookie_jar / 'posix'
        e_c = {
                 "key":"value
        }
        cookiecutter(str(activator_cookie), no_input=True, extra_context=e_c, output_dir=self._home)
```
Unfortunately the templated files are `-rw-r--r--`.

Is there a way to change this using a cookiecutter function?  Or will I have to do it some other way via hook or the `os/pathlib` module?

**Comment by insspb** [comment] 2019-12-22 01:39
Very strange usage of cookiecutter. I think at this moment you cannot set some other permissions during execution, but I can be wrong. 
Anyway I am closing this, as it is not a bug or proposal and was not answered for a long time. I think because everybody just not expect such usage.

**Closed by insspb** 2019-12-22 01:39 UTC
Labels: question
