### ISSUE TITLE
Cookiecutter maintenance

### ISSUE THREAD

**Issue by obvionaoe** [cookiecutter/cookiecutter#1828] opened 2023-03-29 22:42 UTC
cookiecutter seems to be without active maintainers!

A fork ([https://github.com/cookieninja-generator/cookieninja](https://github.com/cookieninja-generator/cookieninja)) was created but also seems to be fairly inactive.

Could we find a way to breathe life into cookiecutter again?

If there's anyway I can help, please let me know.

**Comment by con-f-use** [comment] 2023-04-08 11:23
Among other things, the CI is broken and fails fetching from gitlab.

**Comment by AnuragBalhra** [comment] 2023-04-08 20:12
Does it make sense to have updated [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file for the project?

**Comment by pydanny** [comment] 2023-04-17 08:37
Still following up, haven't forgotten about it.

**Comment by AnuragBalhra** [comment] 2023-04-17 20:59
Just a thought, it would also be good if we could have some "good first issues" marked for the project. 
I'd like to start contributing, but not sure where exactly to begin from.

**Comment by Tamronimus** [comment] 2023-05-05 16:34
> Among other things, the CI is broken and fails fetching from gitlab.
If somewone wants to review and merge my [pull request](https://github.com/cookiecutter/cookiecutter/pull/1838), this problem would be fixed.

**Comment by pydanny** [comment] 2023-05-07 20:32
On Tuesday, May 9, I will see if I can get professional work time to contribute to Cookiecutter. Sorry about the delays.

**Comment by kurtmckee** [comment] 2023-06-10 16:25
@obvionaoe:

> If there's anyway I can help, please let me know.

Aggressively triage open issues.

* **Some issues will be invalid (like reporting an error that has nothing to do with cookiecutter).**

  If possible, try to get the reporter unblocked, perhaps by telling them to upgrade their Python version or install an updated version of cookiecutter or whatever. @-mention some of the maintainers (like @pydanny) and recommend closing the issue with a brief explanation.
* Some issues will be a question (like asking "how do I do such-and-such?").

  Try to get the reporter unblocked, perhaps with a link to the docs or with a snippet of code. @-mention the maintainers and recommend closing the issue.
* Some issues will be addressed by a PR that was already merged.

  Add a comment to cross-reference which PR or commit closed the issue. @-mention the maintainers and recommend closing the issue because it's been fixed.
* If the issue is valid, and you're able to submit a fix, try to fix the issue.

  Keep the PR as small as possible (don't introduce anything that is unrelated). Include tests and documentation in the PR. Be sure to link the PR with the issue so that the issue automatically closes when the PR merges.

The purpose of this type of effort is to give maintainers a 10-second path to issue closure on a silver platter. An hour of your time could help a maintainer close a dozen issues in 2 minutes.

Be gracious and kind, represent yourself (and the project as well) as best you can, and this project can start to move forward again.

----

Now to follow my own advice!

@pydanny I've triaged about 2 dozen open PRs in the last two days. I didn't tag you on all of them but it's the first full page of PRs. Most can be closed, some can be merged. One in particular is extremely dangerous and _must not merge_.

Please close this issue to reduce unintended stress and cognitive burden on yourself and on other maintainers.

### And thanks for your work on cookiecutter!

**Comment by pydanny** [comment] 2023-06-10 21:33
Hey @kurtmckee, I sent you an email. 🙂

**Comment by vemonet** [comment] 2023-07-04 22:57
Hi @kurtmckee , I opened a PR that closes 4 issues to help with the triage :D https://github.com/cookiecutter/cookiecutter/pull/1881

A lot of issues seems to be completely obsolete or out of place like https://github.com/cookiecutter/cookiecutter/issues/1710 it would seems a bit repetitive to go through all issues and send "Obsolete, can close @kurtmckee " for each of them

I think the best is to be a bit harsh, especially with old issues with no activites:
* a maintainer takes 2 hours of its time
* evaluate each issue in 30s and close them (or not). 177*30/60=88.5 minutes, less than 1:30. And after triaging for 20min you'll probably be closing issue in less than 20s ;)
* Don't hesitate to have the issue-closed trigger easy, if you close one by mistake we can still reopen it! The bug is about some installation issues 4 years ago and the folk never followed up? Just close in 10s!

This way you will get it down to less than 30 meaningful issues in less than 2 hours.
And the tips from the closed issues are still there anyway

**Comment by ericof** [comment] 2023-07-12 14:58
We are back ;-)

Closing this issue for now

**Closed by ericof** 2023-07-12 14:58 UTC
Labels: discussion
