### ISSUE TITLE
Allow boolean config variables

### ISSUE THREAD

**Issue by mgaitan** [cookiecutter/cookiecutter#126] opened 2013-11-27 05:05 UTC
`cookiecutter.json` allows a key-value configuration, where value is a string. I would like to ask for a boolean (yes/no) variable to condition a block like this

``` jinja

    {% if use_that_magic %}
         ....
    {% endif %}
```

The easiest way should be autodetect the variable type from the default value. For example 

``` json

{ "full_name": "Martín Gaitán",
  "use_that_magic": true,  
   ...
}
```

When prompt for `use_that_magic` the valid answer should be yes or no. 

Also, could be an attribute `type` when implement #30

**Comment by myyk** [comment] 2015-10-05 23:35
+1 boolean support would be nice.

**Comment by hackebrot** [comment] 2016-12-30 13:44
This would be possible with #848

**Comment by tedmiston** [comment] 2017-03-09 05:13
I'm currently working around lack of boolean support by using a choice variable with strings (`["yes", "no"]`) and `==` string comparisons in Jinja.  This might help others who wind up here looking for bool support.

**Comment by tedmiston** [comment] 2017-03-09 05:27
Another reasonable option, perhaps cleaner, is to use 0 and 1 with Jinja's int filter.  For example...

cookiecutter.json:

```json
{
  "my_bool": 0,
}
```

or 

```json
{
  "my_bool": 1,
}
```

A file in your cookiecutter template:

```jinja
{% if cookiecutter.my_bool|int %}
  my_bool is truthy
{% else %}
  my_bool is falsy
{% endif %}
```

**Comment by jamb0ss** [comment] 2021-12-07 11:15
so is it possible to use bool values with Python actually?
it seems that cookiecutter treats everything like strings, e.g.
`cookiecutter.json` config:
```
{
    "bool_var": false,
}
```
will promt like:
```
bool_var [False]: true
```
will result in `true` in my source code (`{{cookiecutter.bool_var}}`), not `True`
am I missing something?

**Comment by ThatXliner** [comment] 2022-06-13 19:59
Bump.

**Comment by alkatar21** [comment] 2022-06-13 20:04
@ThatXliner I Think this is a duplicate of #1625 which is already implemented with #1626, but not in an official release yet?

**Closed** 2022-06-14 12:54 UTC
Labels: enhancement
